name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Source
      run: |
        apt-get install meson ninja-build gcc-11
        meson setup build
        meson compile -C build


