name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install_project:
    runs-on: ubuntu-latest
    container: gcc:11.4
    steps:
    - uses: actions/checkout@v4
    - name: Build Source
      run: |
        apt-get update
        apt-get -y install build-essential meson ninja-build gcc-arm-none-eabi
        meson setup build --cross-file gba_cross_file.txt
        meson compile -C build


